# -*- coding: utf-8 -*-
"""gdp_prediction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12lsMlicTR83_iRXmIGB8X7sXchyVb391
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression

data = pd.read_csv('/water_potability.csv')

data.info()

sns.regplot(x='Conductivity', y='Organic_carbon', data=data)

lri = LinearRegression()

lri.fit(data[['Conductivity']].values, data.Organic_carbon)

lri.predict([[10]])